config/routes.rb
Getlinks::Application.routes.draw do

  get "/check_username", to: 'users#check_username'

  resource :user, :path => "/:username", :only => [:show, :edit, :update] do
    resource :links, only: [:new, :create, :edit, :update, :destroy] do 
      collection { post :sort }
    end
  end
  
  devise_for :users

  root 'welcome#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  acts_as_list
end

app/models/user.rb
class User < ActiveRecord::Base
	extend FriendlyId
  has_many :links
  mount_uploader :avatar, AvatarUploader
	friendly_id :username

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:login]  ## ------- check --- maybe login??

  validates :username, uniqueness: { :case_sensitive => false }, 
  						format: { with: /\A[a-zA-Z0-9]+\Z/ }, 
  						exclusion: {:in => ["admin", "root", "test", "discover", "view", "find", "search", "list", "all", "post", "users", "guest", "demo", "show", "index", "profile", "edit", "check", "checkname", "username", "api"],:message => "is reserved"},
  						length: {minimum: 3} 

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

    def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
	
  protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected 


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password,:avatar, :avatar_cache) }
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include ApplicationHelper
  include LinksHelper
  
  respond_to :html, :js
  before_filter :auth_user
  before_filter :require_permission

  def new
  	@new_link = Link.new
  end

  def create
  	@link = Link.new(link_params)
  	@link.user = User.friendly.find(params[:username])
  	@link.save
    #@link.move_to_bottom
    @links = @link.user.links.order("position")
  end

  def edit
  end

  def destroy
    @link = Link.find(params[:id])
    @deletedLinkId = @link.id
    @link.remove_from_list if @link
  end

  def sort
    params[:link].each_with_index do |id, index|
      Link.where(id: id).update_all({position: index+1})
    end

    render nothing: true
  end
    
    private

    def link_params
      params.require(:link).permit(:title, :url, :link_type)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  
  respond_to :html, :js

  before_filter :auth_user, :only => [:update]

  def show
  	@user = User.friendly.find(params[:username])
    @links = @user.links.order("position")
    @new_link = Link.new
    session[:return_to] ||= request.referer
  end

  def update
  	@user = User.friendly.find(params[:username])
  	@user.update_attributes(user_params)
	  @links = @user.links.order("position")
    
	respond_to do |format|
	    format.html { redirect_to @user }
	    format.js
  	end
  end


  def check_username
  	if User.where('lower(username) = ?', params[:username].downcase).count == 0
  		render json: true, status: 200
  	else
  		render json: false, status: 400
  	end
  end

  private 

  def user_params
  	params.require(:user).permit(:name, :short_bio, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def auth_user
    unless user_signed_in?
      flash[:alert] = 'You need to be signed in before continuing.'
      redirect_to session.delete(:return_to)
    end
  end
  
end

app/helpers/links_helper.rb
module LinksHelper
	def require_permission
	    if current_user != User.friendly.find(params[:username])
	      redirect_to root_path, :flash => { :alert => "You are not authorized."}
	    end
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Getlinks</title>

		<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
		<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

		<!-- Custom Google Web Font & Font Awesome-->
		<link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
		<link href='https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>

	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

	    <div class="container-fluid main-container">

	      <ul class="nav nav-tabs">
	        <li><%= link_to "Home", root_path %></li>
	        <li><%= link_to "About", root_path %></li>

	         <div class="pull-right user-info">
	           <% if current_user %>
	             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
	           <% else %>
	             <%= link_to "Sign In", new_user_session_path %> or 
	             <%= link_to "Sign Up", new_user_registration_path %>
	           <% end %>
	         </div>

	      </ul>

	       <% if flash[:notice] %>
	         <div class="alert alert-success">
	           <button type="button" class="close" data-dismiss="alert">&times;</button>
	           <%= flash[:notice] %>
	         </div>
	       <% elsif flash[:error] %>
	         <div class="alert alert-danger">
	           <button type="button" class="close" data-dismiss="alert">&times;</button>
	           <%= flash[:error] %>
	         </div>
	       <% elsif flash[:alert] %>
	         <div class="alert alert-warning">
	           <button type="button" class="close" data-dismiss="alert">&times;</button>
	           <%= flash[:alert] %>
	         </div>
	       <% end %>

			<%= yield %>

		</div>
	</body>
</html>

app/views/links/_all_links.html.erb
<div style="text-align: center">
	<span class="horizontal-line"><%= image_tag "line.png" %></span>
	<% links.each do |link| %>
			<div class="col-md-4 col-md-offset-4">
				<% if link.link_type == "normal" %>
					<p><%= link_to link.title.capitalize, link.url, class: "user-link" %></p>
				<% else %>
					<span class="horizontal-line"><%= image_tag "line.png" %></span>
				<% end %>
			</div>
	<% end %>
</div>

app/views/links/_all_links_edit.html.erb
<div style="text-align: center"  id="user-links" data-update-url="<%= sort_user_links_url %>">
	<span class="horizontal-line"><%= image_tag "line.png" %></span>
	<% links.each do |link| %>
		<div data-link="<%= link.id %>" id="link_<%= link.id %>" class="row test-class">
			<div class="col-md-4 col-md-offset-4">
				<% if link.link_type == "normal" %>
					<p><span class="handle"><%= image_tag "draggable.png" %></span></span><%= link_to link.title.capitalize, link.url, class: "user-link" %></p>
				<% else %>
					<p><span class="handle"><%= image_tag "draggable.png" %></span><span class="horizontal-line"><%= image_tag "line.png" %></span></p>
				<% end %>
			</div>

			<div class="col-md-1">
					<%= link_to user_links_path(id: link.id), method: :delete, id: "delete-link" + link.id.to_s, style: "display:none;", remote: true do %>
						<i class="fa fa-trash-o fa-2x"></i>
					<% end %>
			</div>
		</div>


	<% end %>
</div>

app/views/links/_new_link_form.html.erb
<%= form_for :link, remote: true, :url => {controller: "links", action: "create", html: {method: :post}} do |f| %>
	<div class="col-md-1  col-md-offset-3">
		<%= f.check_box :link_type, {class: "divider-checkbox"}, "divider", "normal" %> Divider
	</div>
	
	<div class="col-md-2" id="link-title-div">
			<%= f.text_field :title, placeholder: "Title", class: "form-control" %>
	</div>

	<div class="col-md-2" id="link-url-div">
			<%= f.text_field :url, placeholder: "URL", class: "form-control" %>
	</div>			
			
	<div id="newLinkDivider" style="display:none" class="col-md-2 col-md-offset-1">
		<hr width="150px">
	</div>​


	<div class="col-md-1">
			<%= f.submit 'Save', id: "link-submit-button", :class=>"btn btn-primary" %>
	</div>	
	
<% end %>

app/views/links/create.js.erb
$('#link-form').fadeOut(150);
$('#user-links').replaceWith("<%= j (render partial: 'links/all_links_edit', locals: { links: @links }) %>");

// Call sortable function to make the re rendered list sortable again.
sortableList();

app/views/links/destroy.js.erb
// Remove the deleted row from page
$('div[data-link]').each( function(){
    if ($(this).data("link") == <%= @deletedLinkId %>) {
        $(this).fadeOut(150);
    }
});

app/views/links/edit.html.erb
<h1>Links#edit</h1>
<p>Find me in app/views/links/edit.html.erb</p>

app/views/links/new.js.erb
$('#link-form').html("<%= j (render partial: 'links/new_link_form') %>");
$('#link-form').fadeIn(300);

app/views/users/_new_avatar_modal.html.erb
<%= form_for(@user, :html => {:method => :put, :multipart => true}) do |f|  %>

	<!-- Modal -->
	<div class="modal fade" id="picChangeModal" tabindex="-1" role="dialog" aria-labelledby="picChangeModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h2 class="modal-title" id="picChangeModalLabel">Change pic</h2>
				</div>
				<div class="modal-body">
					<!-- Form for bid -->
					<div class="row">
						<div class="col-md-10 col-md-offset-1">
							<div class="form-horizontal" role="form">
								<%= f.hidden_field :avatar_cache %>
								<div class="form-group">
									<div class="col-md-5 col-md-offset-3">
									  <% if current_user.avatar.url.present? %>
									    <%= image_tag(current_user.avatar.url)  %>
									  <% end %>
									</div>
								</div>

								<div class="form-group">
									<div class="col-md-8 col-md-offset-1">
										<%= f.file_field :avatar %>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- End form for bid -->
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<%= f.submit "Update", :class => "btn btn-primary" %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_user_info.html.erb
<div id="user_info">

		<div class="container-fluid">

			<div class="row">
				<div style="text-align: center">
					<%= image_tag(user.avatar.url, :size=>"300x300", :class=>"img-circle") %>
				</div>
			</div>
			<div class="row">
				<div  style="text-align: center">
					<h1 class="name"><%= user.name %></h1>
				</div>
			</div>
			<div class="row">
				<div style="text-align: center">
					<p class="hint"><%= user.short_bio %></p>
				</div>
			</div>
			<div class="row">
				<div style="text-align: center">
					<p class="username">@<%= user.username %></p>
				</div>
			</div>
			<div class="row">
				<%= render partial: 'links/all_links', locals: { links: links } %>
			</div>
		</div>
</div>

app/views/users/_user_info_edit.html.erb
<div id="user_info_edit" style="display:none;">
	<%= form_for(user, remote: true, :html => {:method => :put, :multipart => true}) do |f| %>
		<div class="container-fluid">

			<div class="row">
				<div class="col-md-2 col-md-offset-7">
					<%= f.submit 'Done editing', :id => 'submit_button', :class=>"btn btn-primary" %>
				</div>
			</div>

			<div class="row">
				<div  style="text-align: center">
					<%= f.file_field :avatar %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-md-offset-5	">
					<%= f.hidden_field :avatar_cache %>
					<%= image_tag(user.avatar.url, :size=>"300x300", :class=>"img-circle") %>
				</div>
			</div>
			<div class="row">
				<div  style="text-align: center">
					<h1><%= f.text_field :name, class: "name", style: "text-align: center" %></h1>
				</div>
			</div>
			<div class="row">
				<div style="text-align: center">
					<p><%= f.text_field :short_bio, class: "hint", style: "text-align: center" %></p>
				</div>
			</div>
			<div class="row">
				<div style="text-align: center">
					<p class="username">@<%= user.username %></p>
				</div>
			</div>

		<% end %>
			<div class="row">
				<%= render partial: 'links/all_links_edit', locals: { links: links } %>
			</div>
		</div>

		<div class="container-fluid">
			<div class="row">
					<div style="text-align: center">
						<div id="link-form" style="display:none;"></div>
					</div>
			</div>
			
			<div class="row">
				<div style="text-align: center">
					<%= link_to new_user_links_path, class: "fa-stack fa-lg link-to-add-new-link", remote: true do %>
						<i class="fa fa-circle-thin fa-stack-2x"></i>
						<i class="fa fa-plus fa-stack-1x"></i>
					<% end %>
				</div>
			</div>
		</div>
<div>

app/views/users/show.html.erb
<a href="#" id="edit_user_info_link">Edit</a>

<%= render partial: 'user_info', :locals => { user: @user, links: @links }  %>

<%= render partial: 'user_info_edit', :locals => { user: @user, links: @links } %>

app/views/users/update.js.erb
$('#user_info').replaceWith("<%= escape_javascript(render partial: 'user_info', :locals => { user: @user, links: @links }) %>");
$('#user_info_edit').replaceWith("<%= escape_javascript(render  partial: 'user_info_edit', :locals => { user: @user, links: @links }) %>");


$('#user_info_edit').hide(); 
$('#user_info').show(); 

// Call sortable function to make the re rendered list sortable again.
sortableList();

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>